[package]
name = "at-cryptoauth"
version = "0.1.0"
authors = ["Kei Shirakizawa <ks@blackbird.online>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/at-cryptoauth-rs"
documentation = "https://docs.rs/at-cryptoauth"
description = "Driver for ATECC608 Crypto Authentication secure elements"
edition = "2018"

[dependencies]
crc = "2.0.0-rc.1"
heapless = { version = "^0.5", features = ["serde"] }
generic-array = "0.14.4"
env_logger = { version = "0.8.1", optional = true }
linux-embedded-hal = { version = "0.3.0", optional = true }
log = { version = "0.4.0", optional = true }
openssl = { version = "0.10.30", features = ["vendored"], optional = true }

[dependencies.embedded-hal]
version = "1.0.0-alpha.4"

[dependencies.signature]
version = "1.2.2"
default-features = false

[dependencies.digest]
version = "0.9.0"
default-features = false

[dev-dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
cortex-m-semihosting = "0.3.5"
panic-halt = "0.2.0"
panic-semihosting = "0.5.0"

[dev-dependencies.stm32l4xx-hal]
git = "https://github.com/BlackbirdHQ/stm32l4xx-hal"
branch = "factbird-mini-1.0"
features = ["rt", "stm32l4x5"]

[features]
std = ["env_logger", "linux-embedded-hal", "log", "openssl"]

[[example]]
name = "raspberrypi_atecc608"
required-features = ["std"]
