[package]
name = "at-cryptoauth"
version = "0.1.0"
authors = ["Kei Shirakizawa <ks@blackbird.online>"]
edition = "2018"

[dependencies]
crc = "2.0.0-rc.1"
heapless = { version = "^0.5", features = ["serde"] }

[dependencies.signature]
version = "1.2.2"
default-features = false

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]

[dev-dependencies.stm32l4xx-hal]
git = "https://github.com/BlackbirdHQ/stm32l4xx-hal.git"
branch = "i2c-enhancement-pr-to-be-made"
features = ["rt", "stm32l4x5"]
